apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: {{ .Values.namespaces.registry }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .Values.registryImagePullSecretsNamespaces | quote }}
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ .Values.registryImagePullSecretsNamespaces | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "hue-chart.imagePullSecret" .Values.secrets.registry }}