apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-registry
  namespace: {{ .Values.namespaces.registry }}
spec:
  stripPrefix:
    prefixes:
      - /registry
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-registry
  namespace: {{ .Values.namespaces.registry }}
spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: {{ .Values.tlsSecret }}
  routes:
    - kind: Rule
      match: Host("{{ .Values.hosts.registry }}") 
      services:
        - name: registry-service
          port: 5000
    - kind: Rule
      match: Host("{{ .Values.hosts.local }}") && PathPrefix("/registry")
      middlewares:
        - name: strip-registry
      services:
        - name: registry-service
          port: 5000