{{ if .Values.tags.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth-secret
  namespace: {{ .Values.namespaces.registry }}
type: Opaque
data:
  htpasswd: {{ include "hue-chart.htpasswd" .Values.secrets.registry.auth }}
{{ end }}