apiVersion: v1
kind: Secret
metadata:
  name: registry-auth-secret
  namespace: {{ .Values.namespaces.registry }}
type: Opaque
data:
  htpasswd: {{ .Values.secrets.registryBasicAuth | b64enc | quote }}