{{ if .Values.tags.hue }}
apiVersion: v1
kind: Secret
metadata:
  name: hue-express-secret
  namespace: {{ .Values.namespaces.hue }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.hueExpress }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hue-express-huebridge-cacert
  namespace: {{ .Values.namespaces.hue }}
type: Opaque
data:
  huebridge_cacert.pem: {{ .Values.secrets.hueBridgeCaCert | b64enc | quote }}
{{ end }}