{{ if .Values.tags.hue }}
apiVersion: v1
kind: Secret
metadata:
  name: rust-hue-schedule
  namespace: {{ .Values.namespaces.hue }}
type: Opaque
data:
  schedule.yml: {{ toYaml .Values.secrets.rustSchedule | b64enc | quote }}
{{ end }}