apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-hue
  namespace: {{ .Values.namespaces.hue }}
  labels:
    app: rust-hue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-hue
  template:
    metadata:
      labels:
        app: rust-hue
    spec:
      containers:
        - name: rust-container
          image: {{ .Values.hosts.registry }}/rust-hue:arm-latest
          ports:
            - containerPort: 8000
              name: rocket-port
          env:
            - name: SCHEDULE_YAML_PATH
              value: /data/schedule.yml
          volumeMounts:
            - name: rust-hue-schedule
              mountPath: /data/
          resources:
            {{- toYaml .Values.imageResources.rust | nindent 12 }}
      volumes:
        - name: rust-hue-schedule
          secret:
            secretName: rust-hue-schedule
      imagePullSecrets:
        - name: image-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rust-hue-service
  namespace: {{ .Values.namespaces.hue }}
spec:
  type: ClusterIP
  selector:
    app: rust-hue
  ports:
  - port: 8000
    targetPort: 8000