# Default values. Must be filled in.

hosts:
  registry: "{{ .Values.secrets.registry.host }}"
  main: example.org
  local: 127.0.0.1

tlsSecret:

tags:
  hue: true
  registry: true
  traefik: true
  certManager: true # You'll probably want to turn this off to install CRDs first, then turn back on.
  ddnsUpdater: true

namespaces:
  hue: default
  registry: registry
  traefik: kube-system
  certManager: cert-manager

livenessProbePeriodSeconds:
  hue: 37
  rust: 37
  registry: 127

# Copy the image-pull-secret to the following namespaces
registryImagePullSecretsNamespaces:

cert-manager:
  namespace: cert-manager
  installCRDs: true

ddns-updater:
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              CONFIG: "{{ .Values.innerConfig | toJson }}"
              PERIOD: "60m"
  innerConfig:

# Specific to our configs
certManager:
  tlsNamespaces: 
  server:
  privateKeySecretName:

imageResources:
  rust:
    limits:
      memory: "512Mi"
      cpu: "100m"
  hueExpress:
    limits:
      memory: "512Mi"
      cpu: "100m"
  registry:
    limits:
      memory: "256Mi"
      cpu: "100m"

reflector:
  resources:
    limits:
      memory: "512Mi"
      cpu: "100m"

secrets:
  hueAuth:
    username: example
    password: password
  traefikAuth:
    username: example
    password: password
  rustSchedule:
    location:
    schedule:
  hueExpress:
  hueBridgeCaCert: certGoesHere
  registry:
    auth:
      username: example
      password: password
    host:
    persistentStoragePath: