# Default values. Must be filled in.

hosts:
  registry: "{{ .Values.secrets.registry.host }}"
  main: example.org
  local: 127.0.0.1

tlsSecret:

enabled:
  hue: true
  registry: true
  traefik: true

namespaces:
  hue: default
  registry: registry
  traefik: kube-system

livenessProbePeriodSeconds:
  hue: 37
  rust: 37
  registry: 127

# Copy the image-pull-secret to the following namespaces
registryImagePullSecretsNamespaces:

imageResources:
  rust:
    limits:
      memory: "512Mi"
      cpu: "100m"
  hueExpress:
    limits:
      memory: "512Mi"
      cpu: "100m"
  registry:
    limits:
      memory: "256Mi"
      cpu: "100m"

secrets:
  hueAuth:
    username:
    password:
  traefikAuth:
    username:
    password:
  rustSchedule:
    location:
    schedule:
  hueExpress:
  hueBridgeCaCert:
  registry:
    auth:
      username:
      password:
    host:
    persistentStoragePath: