#! /bin/bash

function debug() (
	set -ex
	docker-compose --build up
)

function buildx() (
	set -ex
	docker buildx build -t rust-hue:arm-1.0 --platform linux/arm64 --output=type=docker .
)

function publish() (
	set -ex
	docker tag rust-hue:arm-1.0 registry.blahblahblah.xyz/rust-hue:arm-1.0
	docker push registry.blahblahblah.xyz/rust-hue:arm-1.0
)

function all() (
	buildx
	publish
)

$*